// ── POTUS Game Data ──

const DATA = {

  politicians: [
    {id:'trump',n:'Donald Trump',p:'R',i:'DT',d:'45th & 47th President',base:54,bio:'Real estate mogul turned populist president. Known for America First trade policy, immigration crackdowns, and commanding rallies.',issues:['immigration','economy','america first','energy'],sb:{TX:8,FL:7,OH:5,PA:3,WI:3}},
    {id:'biden',n:'Joe Biden',p:'D',i:'JB',d:'46th President',base:47,bio:'Career senator and former VP turned president. Known for union ties, foreign policy experience, and bipartisan dealmaking.',issues:['democracy','healthcare','climate','unions'],sb:{PA:5,MI:5,WI:4,MN:4,DE:9}},
    {id:'harris',n:'Kamala Harris',p:'D',i:'KH',d:'Former Vice President',base:45,bio:'First woman, Black, and South Asian VP. Former prosecutor and California AG. Strong on abortion rights and equality.',issues:['abortion rights','equality','economy','climate'],sb:{CA:5,NV:4,AZ:4,GA:3}},
    {id:'desantis',n:'Ron DeSantis',p:'R',i:'RD',d:'Governor, Florida',base:47,bio:'Harvard Law, Navy JAG, two-term Florida governor. Waged high-profile fights against Disney, school curricula, and vaccine mandates.',issues:['education freedom','anti-woke','border','taxes'],sb:{FL:9,TX:5,SC:5,TN:5}},
    {id:'aoc',n:'Alexandria Ocasio-Cortez',p:'D',i:'AO',d:'Congresswoman, NY-14',base:42,bio:'Bartender turned congresswoman. Democratic Socialist from the Bronx. Architect of the Green New Deal. DSA member.',issues:['green new deal','medicare for all','housing','student debt'],sb:{NY:6,CA:5,MA:5,CO:4,VT:5}},
    {id:'romney',n:'Mitt Romney',p:'R',i:'MR',d:'Former Senator, Utah',base:44,bio:'Former Massachusetts governor, 2012 GOP nominee, and one of Trump\'s most vocal Republican critics. Moderate conservative.',issues:['bipartisanship','fiscal responsibility','nato','rule of law'],sb:{UT:9,ME:5,NH:4,VA:3}},
    {id:'newsom',n:'Gavin Newsom',p:'D',i:'GN',d:'Governor, California',base:45,bio:'Third-generation California politician. Turned San Francisco into a national test case for progressive governance.',issues:['climate','housing','progressive values','tech economy'],sb:{CA:9,WA:5,OR:5,CO:4}},
    {id:'scott',n:'Tim Scott',p:'R',i:'TS',d:'Senator, South Carolina',base:46,bio:'First Black Republican senator from the South since Reconstruction. Inspirational rags-to-riches story. Faith-forward politics.',issues:['opportunity','faith','border','economy'],sb:{SC:9,GA:4,NC:5,AL:5}},
    {id:'warren',n:'Elizabeth Warren',p:'D',i:'EW',d:'Senator, Massachusetts',base:43,bio:'Harvard Law professor turned senator. Architect of the Consumer Financial Protection Bureau. Known for detailed policy plans.',issues:['wealth tax','student debt','healthcare','climate'],sb:{MA:9,VT:6,RI:5,ME:4}},
    {id:'haley',n:'Nikki Haley',p:'R',i:'NH',d:'Former UN Ambassador',base:46,bio:'First Indian-American and first female governor of South Carolina. US Ambassador to the UN under Trump.',issues:['national security','fiscal responsibility','border','china policy'],sb:{SC:7,VA:4,NH:5,NC:4}},
    {id:'kennedy',n:'RFK Jr.',p:'I',i:'RK',d:'Independent',base:39,bio:'Environmental lawyer, vaccine skeptic, and scion of the Kennedy dynasty. Ran in 2024 as independent.',issues:['vaccine freedom','anti-establishment','environment','peace'],sb:{NH:5,VT:4,ME:4,AK:4}},
    {id:'christie',n:'Chris Christie',p:'R',i:'CC',d:'Former Governor, NJ',base:43,bio:'Blunt, combative two-term NJ governor and federal prosecutor. Known for bridgegate, Trump feud, and town-hall brutality.',issues:['law & order','anti-corruption','economy','nato'],sb:{NJ:6,NH:5,PA:4,OH:3}},
    {id:'vance',n:'JD Vance',p:'R',i:'JV',d:'Senator & 50th Vice President',base:48,bio:'Author of Hillbilly Elegy. Became Trump\'s VP pick in 2024. Ohio senator representing the Rust Belt working class.',issues:['america first','trade','anti-war','working class'],sb:{OH:8,PA:5,MI:4,WI:4}},
    {id:'rubio',n:'Marco Rubio',p:'R',i:'MR2',d:'Secretary of State',base:48,bio:'Cuban-American senator from Florida. Foreign policy hawk. Ran against Trump in 2016 and became his Secretary of State.',issues:['national security','anti-communism','immigration reform','latin america policy'],sb:{FL:7,NV:5,AZ:4,TX:5}},
    {id:'kelly',n:'Mark Kelly',p:'D',i:'MK',d:'Senator & Astronaut, Arizona',base:47,bio:'Navy combat pilot, NASA astronaut, husband of shooting survivor Gabby Giffords. Arizona senator since 2020.',issues:['gun safety','veterans','nasa & space','border security'],sb:{AZ:8,NV:5,CO:4,PA:3}},
    {id:'warnock',n:'Raphael Warnock',p:'D',i:'RW',d:'Senator, Georgia',base:46,bio:'Senior pastor at Ebenezer Baptist Church in Atlanta — the same pulpit as MLK. Won Georgia\'s 2020 runoff against all odds.',issues:['voting rights','healthcare','faith & justice','economy'],sb:{GA:9,SC:3,NC:4,VA:3}},
    {id:'ossoff',n:'Jon Ossoff',p:'D',i:'JO',d:'Senator, Georgia',base:45,bio:'Youngest US senator elected in decades. Investigative journalist turned politician. Ran with Warnock in historic Georgia runoffs.',issues:['democracy','clean energy','anti-corruption','tech economy'],sb:{GA:8,VA:4,NC:3,FL:2}},
    {id:'mamdani',n:'Zohran Mamdani',p:'D',i:'ZM',d:'Mayor of New York City',base:40,bio:'Democratic Socialist NYC mayor. Son of filmmaker Mira Nair. Won historic 2025 upset over Cuomo. Runs on radical affordability agenda.',issues:['affordability','housing','free transit','wealth tax'],sb:{NY:10,MA:6,VT:6,CA:4}},
  ],

  states: [
    {name:'Alabama',abbr:'AL',ev:9,lean:'R',issue:'economy & faith values',base:37},
    {name:'Alaska',abbr:'AK',ev:3,lean:'R',issue:'energy & federal land',base:41},
    {name:'Arizona',abbr:'AZ',ev:11,lean:'swing',issue:'immigration & cost of living',base:50},
    {name:'Arkansas',abbr:'AR',ev:6,lean:'R',issue:'economy & rural healthcare',base:36},
    {name:'California',abbr:'CA',ev:54,lean:'D',issue:'housing & climate',base:64},
    {name:'Colorado',abbr:'CO',ev:10,lean:'D',issue:'climate & economy',base:56},
    {name:'Connecticut',abbr:'CT',ev:7,lean:'D',issue:'healthcare & economy',base:59},
    {name:'Delaware',abbr:'DE',ev:3,lean:'D',issue:'economy & environment',base:60},
    {name:'Florida',abbr:'FL',ev:30,lean:'R',issue:'immigration & cost of living',base:41},
    {name:'Georgia',abbr:'GA',ev:16,lean:'swing',issue:'economy & voting rights',base:50},
    {name:'Hawaii',abbr:'HI',ev:4,lean:'D',issue:'tourism economy & climate',base:66},
    {name:'Idaho',abbr:'ID',ev:4,lean:'R',issue:'federal land & gun rights',base:34},
    {name:'Illinois',abbr:'IL',ev:19,lean:'D',issue:'economy & crime',base:58},
    {name:'Indiana',abbr:'IN',ev:11,lean:'R',issue:'manufacturing & economy',base:38},
    {name:'Iowa',abbr:'IA',ev:6,lean:'R',issue:'farming & rural economy',base:44},
    {name:'Kansas',abbr:'KS',ev:6,lean:'R',issue:'agriculture & economy',base:38},
    {name:'Kentucky',abbr:'KY',ev:8,lean:'R',issue:'coal & rural economy',base:36},
    {name:'Louisiana',abbr:'LA',ev:8,lean:'R',issue:'energy & economy',base:37},
    {name:'Maine',abbr:'ME',ev:4,lean:'D',issue:'fishing economy & healthcare',base:53},
    {name:'Maryland',abbr:'MD',ev:10,lean:'D',issue:'federal jobs & education',base:64},
    {name:'Massachusetts',abbr:'MA',ev:11,lean:'D',issue:'healthcare & education',base:65},
    {name:'Michigan',abbr:'MI',ev:15,lean:'swing',issue:'auto industry & economy',base:50},
    {name:'Minnesota',abbr:'MN',ev:10,lean:'D',issue:'economy & healthcare',base:53},
    {name:'Mississippi',abbr:'MS',ev:6,lean:'R',issue:'economy & poverty',base:37},
    {name:'Missouri',abbr:'MO',ev:10,lean:'R',issue:'economy & rural issues',base:40},
    {name:'Montana',abbr:'MT',ev:4,lean:'R',issue:'land rights & energy',base:38},
    {name:'Nebraska',abbr:'NE',ev:5,lean:'R',issue:'agriculture & economy',base:38},
    {name:'Nevada',abbr:'NV',ev:6,lean:'swing',issue:'cost of living & housing',base:50},
    {name:'New Hampshire',abbr:'NH',ev:4,lean:'swing',issue:'economy & independence',base:50},
    {name:'New Jersey',abbr:'NJ',ev:14,lean:'D',issue:'taxes & cost of living',base:56},
    {name:'New Mexico',abbr:'NM',ev:5,lean:'D',issue:'immigration & economy',base:54},
    {name:'New York',abbr:'NY',ev:28,lean:'D',issue:'crime & economy',base:60},
    {name:'North Carolina',abbr:'NC',ev:16,lean:'swing',issue:'economy & healthcare',base:50},
    {name:'North Dakota',abbr:'ND',ev:3,lean:'R',issue:'energy & agriculture',base:34},
    {name:'Ohio',abbr:'OH',ev:17,lean:'R',issue:'manufacturing & economy',base:45},
    {name:'Oklahoma',abbr:'OK',ev:7,lean:'R',issue:'energy & economy',base:35},
    {name:'Oregon',abbr:'OR',ev:8,lean:'D',issue:'housing & climate',base:57},
    {name:'Pennsylvania',abbr:'PA',ev:19,lean:'swing',issue:'economy & healthcare',base:50},
    {name:'Rhode Island',abbr:'RI',ev:4,lean:'D',issue:'economy & healthcare',base:60},
    {name:'South Carolina',abbr:'SC',ev:9,lean:'R',issue:'economy & military',base:38},
    {name:'South Dakota',abbr:'SD',ev:3,lean:'R',issue:'agriculture & economy',base:36},
    {name:'Tennessee',abbr:'TN',ev:11,lean:'R',issue:'economy & gun rights',base:37},
    {name:'Texas',abbr:'TX',ev:40,lean:'R',issue:'border & energy economy',base:40},
    {name:'Utah',abbr:'UT',ev:6,lean:'R',issue:'economy & federal land',base:41},
    {name:'Vermont',abbr:'VT',ev:3,lean:'D',issue:'healthcare & climate',base:67},
    {name:'Virginia',abbr:'VA',ev:13,lean:'D',issue:'federal jobs & economy',base:54},
    {name:'Washington',abbr:'WA',ev:12,lean:'D',issue:'tech economy & climate',base:61},
    {name:'West Virginia',abbr:'WV',ev:4,lean:'R',issue:'coal & rural economy',base:33},
    {name:'Wisconsin',abbr:'WI',ev:10,lean:'swing',issue:'farming & manufacturing',base:50},
    {name:'Wyoming',abbr:'WY',ev:3,lean:'R',issue:'energy & federal land',base:30},
  ],

  countries: [
    {name:'Afghanistan',flag:'🇦🇫',rank:47,strength:28,nuclear:false,allies:['Pakistan'],pop:42,gdp:20,desc:'Mountainous terrain, asymmetric warfare, Taliban insurgency. Historical graveyard of empires.'},
    {name:'China',flag:'🇨🇳',rank:3,strength:92,nuclear:true,allies:['Russia','North Korea'],pop:1400,gdp:18000,desc:'World\'s largest army (2M active). Advanced tech, stealth fighters, nuclear triad, massive cyber capabilities. Near-peer adversary.'},
    {name:'Russia',flag:'🇷🇺',rank:2,strength:94,nuclear:true,allies:['China','Belarus'],pop:145,gdp:1900,desc:'Nuclear superpower with 6,000+ warheads. Battle-hardened from Ukraine. Experienced in chemical & electronic warfare.'},
    {name:'North Korea',flag:'🇰🇵',rank:34,strength:42,nuclear:true,allies:['China','Russia'],pop:25,gdp:18,desc:'1.2M active troops. Underground tunnels, nuclear-tipped ICBMs, unpredictable regime. Seoul is 35 miles from the border.'},
    {name:'Iran',flag:'🇮🇷',rank:14,strength:62,nuclear:false,allies:['Russia','Syria'],pop:87,gdp:367,desc:'Ballistic missiles, Hezbollah proxies, drone swarms. Controls Strait of Hormuz — global oil chokepoint.'},
    {name:'Iraq',flag:'🇮🇶',rank:55,strength:30,nuclear:false,allies:[],pop:42,gdp:264,desc:'Rebuilding military after ISIS war. Iran-backed militias operate independently. Oil-rich but politically fragile.'},
    {name:'Syria',flag:'🇸🇾',rank:68,strength:22,nuclear:false,allies:['Iran','Russia'],pop:18,gdp:11,desc:'Fractured military after 13-year civil war. Russian air bases still active. Chemical weapons history.'},
    {name:'Venezuela',flag:'🇻🇪',rank:52,strength:31,nuclear:false,allies:['Cuba','Russia'],pop:29,gdp:98,desc:'Government-loyal armed forces. Cuba-trained intelligence. Economic collapse limits capabilities.'},
    {name:'Cuba',flag:'🇨🇺',rank:63,strength:20,nuclear:false,allies:['Russia','Venezuela'],pop:11,gdp:107,desc:'Small but ideologically disciplined force. Russian intelligence cooperation. 90 miles from Florida.'},
    {name:'Somalia',flag:'🇸🇴',rank:112,strength:8,nuclear:false,allies:[],pop:17,gdp:8,desc:'Al-Shabaab controls large territory. Weak federal government. US special forces already present.'},
    {name:'Libya',flag:'🇱🇾',rank:78,strength:15,nuclear:false,allies:[],pop:7,gdp:51,desc:'Rival governments and militias. Wagner Group mercenaries present. No unified command structure.'},
    {name:'Pakistan',flag:'🇵🇰',rank:9,strength:72,nuclear:true,allies:['China'],pop:230,gdp:374,desc:'150+ nuclear warheads. Large army. Complicated US-Pakistan relationship. Borders Afghanistan and India.'},
    {name:'India',flag:'🇮🇳',rank:4,strength:88,nuclear:true,allies:['US','France'],pop:1400,gdp:3700,desc:'4th strongest military. 1.45M active troops. Nuclear-armed. Generally a US partner — war would be catastrophic.'},
    {name:'Mexico',flag:'🇲🇽',rank:38,strength:36,nuclear:false,allies:['US'],pop:130,gdp:1328,desc:'Cartel insurgencies drain military capacity. Shared 2,000-mile border. Economic integration would make conflict devastating.'},
    {name:'Saudi Arabia',flag:'🇸🇦',rank:13,strength:63,nuclear:false,allies:['US','UAE'],pop:36,gdp:1062,desc:'Advanced US-supplied F-15s and Patriot missiles. Massive defense budget. Controls 17% of world oil.'},
    {name:'Israel',flag:'🇮🇱',rank:17,strength:60,nuclear:true,allies:['US'],pop:9,gdp:521,desc:'Highly advanced IDF with F-35s, Iron Dome, Arrow. Widely believed to have 90+ nukes. US treaty ally.'},
    {name:'Turkey',flag:'🇹🇷',rank:8,strength:73,nuclear:false,allies:['NATO'],pop:85,gdp:906,desc:'NATO\'s 2nd largest army. F-16s, Bayraktar drones. Controls Bosphorus — can block Russian naval access.'},
    {name:'Yemen',flag:'🇾🇪',rank:89,strength:14,nuclear:false,allies:['Iran'],pop:35,gdp:21,desc:'Houthi rebels backed by Iran. Control Red Sea shipping lanes. Drone and missile attacks on US ships.'},
    {name:'Ethiopia',flag:'🇪🇹',rank:44,strength:32,nuclear:false,allies:[],pop:125,gdp:111,desc:'Africa\'s largest army by size. Recovering from Tigray civil war. Horn of Africa strategic position.'},
    {name:'Myanmar',flag:'🇲🇲',rank:50,strength:29,nuclear:false,allies:['China'],pop:54,gdp:65,desc:'Military junta in civil war with resistance forces. China-aligned. Genocide history.'},
  ],

  regions: {
    All: null,
    Swing: ['AZ','GA','MI','NV','NH','NC','PA','WI'],
    Northeast: ['CT','DE','ME','MD','MA','NH','NJ','NY','PA','RI','VT'],
    South: ['AL','AR','FL','GA','KY','LA','MS','NC','SC','TN','TX','VA','WV'],
    Midwest: ['IL','IN','IA','KS','MI','MN','MO','NE','ND','OH','SD','WI'],
    West: ['AK','AZ','CA','CO','HI','ID','MT','NV','NM','OR','UT','WA','WY']
  },

  worldEventTypes: [
    'major earthquake kills thousands',
    'refugee crisis overwhelms European allies',
    'US ally is invaded by a neighbor',
    'global pandemic outbreak in Southeast Asia',
    'nuclear standoff escalates in Asia',
    'military coup overthrows allied government',
    'global financial market crash triggered by debt crisis',
    'famine crisis across sub-Saharan Africa',
    'massive cyberattack cripples US infrastructure',
    'major terrorist attack on a US allied city',
    'oil tanker attacked in Strait of Hormuz',
    'climate disaster: record hurricane devastates US coast',
    'assassination of a key allied leader',
    'China blockades Taiwan Strait',
    'drone swarm attacks US military base overseas',
    'UN Security Council votes on military intervention',
    'mass protest movement destabilizes allied government',
    'space debris damages GPS satellite network',
    'cartel seizes control of a Mexican border city',
    'biological weapons facility reportedly breached'
  ]
};
